---
# handlers file for cic2.2.0


- name: generate new grub config
  shell: grub2-mkconfig -o "{{ cis_grub_bootloader_filename }}"
  check_mode: no
  changed_when: no

- name: reload dconf
  shell: dconf update  
  check_mode: no
  changed_when: no

- name: restart xinetd
  service:
    name: xinetd
    state: restarted  

- name: Restart ntpd
  service:
    name: ntpd
    state: restarted

- name: Restart chronyd
  service:
    name: chronyd
    state: restarted

- name: Restart postfix
  service:
    name: postfix
    state: restarted    

- name: sysctl flush ipv4 route table
  become: yes
  sysctl:
    name: net.ipv4.route.flush
    value: '1'
    sysctl_set: yes    

- name: sysctl flush ipv6 route table
  become: yes
  sysctl:
    name: net.ipv6.route.flush
    value: '1'
    sysctl_set: yes    

- name: grub2cfg
  shell: /sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
  check_mode: no
  changed_when: no

- name: restart firewalld
  service:
    name: firewalld
    state: restarted    

- name: restart auditd
  shell: service auditd restart
  args:
    warn: no
  check_mode: no
  changed_when: no

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart syslog-ng
  service:
    name: syslog-ng
    state: restarted    

- name: restart sshd
  service:
    name: sshd
    state: restarted    