---
# Precheck is used to check environment before run all the Tasks 

- name: Pre|Check OS version and family
  fail:
    msg: "This benchmark can only be run against RHEL 7. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version is version('7', '!=')

- name: Pre|Check ansible version
  fail:
      msg: You must use ansible 2.7 or greater
  when: not ansible_version.full is version('2.7', '>=')

- name: Pre|Check full version
  shell: cat /etc/redhat-release
  register: redhat_version
  changed_when: no
  check_mode: no
  tags:
    - redhat_version  
