---

- name: 3.2.5|Ensure broadcast ICMP requests are ignored 
  sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
  notify: sysctl flush ipv4 route table
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 