---

- name: 3.3.1|Ensure IPv6 router advertisements are not accepted 
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
  with_items:
      - { name: net.ipv6.conf.all.accept_ra, value: 0 }
      - { name: net.ipv6.conf.default.accept_ra, value: 0 }
  notify: sysctl flush ipv6 route table
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation
    - RULE