---

- name: 3.4.4|Ensure permissions on /etc/hosts.allow are configured 
  file:
    dest: /etc/hosts.allow
    owner: root
    group: root
    mode: 0644
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 