---

- name: 3.4.5|Ensure permissions on /etc/hosts.deny are configured 
  file:
    dest: /etc/hosts.deny
    owner: root
    group: root
    mode: 0644
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE    