---

- name: 3.5.1|Ensure DCCP is disabled 
  lineinfile:
    path: "{{ cis_modprobe_conf_filename }}"
    regexp: "^(#)?install dccp(\\s|$)"
    line: "install dccp /bin/true"
    create: yes
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation
    - RULE 
