---

- name: 3.6.4|Ensure outbound and established connections are configured 
  debug:
    msg: "WARNING - This check has not been implemented yet."
  when: cis_firewall == "firewalld"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE        

- name: 3.6.4|Ensure outbound and established connections are configured 
  iptables:
    chain: '{{ chain }}'
    protocol: '{{ protocol }}'
    match: '{{ match }}'
    ctstate: '{{ ctstate }}'
    jump: '{{ jump }}'
    action: append
  when: cis_firewall == "iptables"
  with_items:
    - {chain: OUTPUT, protocol: tcp, match: state, ctstate: NEW,ESTABLISHED, jump: ACCEPT}
    - {chain: OUTPUT, protocol: udp, match: state, ctstate: NEW,ESTABLISHED, jump: ACCEPT}
    - {chain: OUTPUT, protocol: icmp, match: state, ctstate: NEW,ESTABLISHED, jump: ACCEPT}
    - {chain: INPUT, protocol: tcp, match: state, ctstate: ESTABLISHED, jump: ACCEPT}
    - {chain: INPUT, protocol: udp, match: state, ctstate: ESTABLISHED, jump: ACCEPT}
    - {chain: INPUT, protocol: icmp, match: state, ctstate: ESTABLISHED, jump: ACCEPT}
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation
    - RULE 