---

- name: 3.6.5|Ensure firewall rules exist for all open ports 
  firewalld:
    service: "{{ item }}"
    state: enabled
    zone: drop
    permanent: true
    immediate: true
  with_items: "{{ cis_firewall_services }}"
  notify: restart firewalld
  when: cis_firewall == "firewalld"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

- name: 3.6.5|Ensure firewall rules exist for all open ports 
  iptables:
    chain: INPUT
    protocol: "{{ protocol }}"
    destination_port: "{{ destination_port }}"
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: "{{ comment }}"
    match: state
    action: append
  with_items: "{{ cis_firewall_rules_for_open_connection }}"
  when: cis_firewall == "iptables"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE    