---
#SB
# - name: 1.1.15|Check /dev/shm exist
#   set_fact:
#     dev_shm_exist: "{{ '/dev/shm' in  mountpoints }}"
#   tags:
#     - AUDITPRECHECK
#     - REMEDIATEPRECHECK

- name: 1.1.15|task01
  set_fact:
    dev_shm_partition_opt: "{{ dev_shm_partition_opt + ['nodev'] }}"
  when: is_compliance or is_remediate

- name: 1.1.15|task02
  set_fact:
    nodev_exist_in_dev_shm: "{{ 'nodev' in home_mountpoint_options }}"
  when: is_compliance or is_remediate

###############
#    Audit    #
###############

- name: 1.1.15|task03
  shell: /usr/bin/mount | /usr/bin/grep 'on /dev/shm ' | /usr/bin/awk '{print} END {if (NR == 0) print "failed"}'
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task03
  when: is_compliance

- name: 1.1.15|Ensure nodev option set on /dev/shm partition
  moveit:
    section: 1.1.15
    description: Ensure nodev option set on /dev/shm partition
    info: |
      <pre class="primary">
      If a /dev/shm partition exists run the following command and verify that the nodev option is set on /dev/shm:
      </pre>
      <pre class="secondary">
      # mount | grep /dev/shm
      tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime)
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      mount | grep 'on /dev/shm '
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task03.stdout_lines | difference(["failed"]) | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'passed' if nodev_exist_in_dev_shm else 'failed' }}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation

###############
# Remediation #
###############

- name: 1.1.15|task04
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(dev_shm_partition_opt) | join(',') }}"
  when:
    - is_remediate
    - not nodev_exist_in_dev_shm
    - (item.mount == '/dev/shm')
  with_items: "{{ dev_shm_mountpoints }}"
  register: task04

- name: 1.1.15|Ensure nodev option set on /dev/shm partition
  moveit:
    section: 1.1.15
    description: Ensure nodev option set on /dev/shm partition
    info: |
      <pre class="primary">
      Edit the /etc/fstab file and add nodev to the fourth field (mounting options) for the /dev/shm partition. See the fstab(5) manual page for more information.
      Run the following command to remount /dev/shm :
      </pre>
      <pre class="secondary">
      # mount -o remount,nodev /dev/shm
      </pre>
    cmd_output: |
      {% if not task04.changed %}
      <pre class="primary">Manual intervention required for partition-related controls.</pre>
      {% endif %}
    isRemediate: "{{ is_remediate }}"
    state: "{% if nodev_exist_in_dev_shm %}passed{% elif task04.changed %}changed{% else %}manual{% endif %}"
  when: is_remediate
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation