---
#SB
###############
#    Audit    #
###############

- name: 1.1.23|task01
  shell: /usr/sbin/modprobe -n -v usb-storage 2> /dev/null | /usr/bin/egrep 'install /bin/true' | /usr/bin/awk '{print} END {if (NR == 0) print "failed"}'
  check_mode: no
  changed_when: no
  failed_when: no
  register: task01
  when: is_compliance

- name: 1.1.23| Disable USB Storage
  moveit:
    section: 1.1.23
    description: Disable USB Storage - modprobe
    info: |
      <pre class="primary">
      Run the following commands and verify the output is as indicated:
      </pre>
      <pre class="secondary">
      # modprobe -n -v usb-storage
      install /bin/true
      # lsmod | grep ubs-storage
      &lt;No output&gt;
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      modprobe -n -v usb-storage | egrep 'install /bin/true'
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task01.stdout_lines | difference(["failed"]) | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'passed' if ('install /bin/true' in task01.stdout_lines|trim) else 'failed' }}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level2_Workstation

- name: 1.1.23|task02
  shell: /usr/sbin/lsmod | /usr/bin/grep usb-storage | /usr/bin/awk 'END {if (NR == 0) print "passed" ; else print "failed"}'
  check_mode: no
  changed_when: no
  failed_when: no
  register: task02
  when: is_compliance

- name: 1.1.23| Disable USB Storage
  moveit:
    section: 1.1.23
    description: Disable USB Storage - lsmod
    info: |
      <pre class="primary">
      Run the following commands and verify the output is as indicated:
      </pre>
      <pre class="secondary">
      # modprobe -n -v usb-storage
      install /bin/true
      # lsmod | grep usb-storage
      &lt;No output&gt;
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      lsmod | grep ubs-storage | awk 'END {if (NR == 0) print "passed" ; else print "failed"}'
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task02.stdout }}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ task02.stdout }}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level2_Workstation

###############
# Remediation #
###############

- name: 1.1.23|task03
  stat:
    path: "{{ cis_modprobe_usb_filename }}"
  register: task03
  when: is_remediate

- name: 1.1.23|task04
  lineinfile:
    path: "{{ cis_modprobe_usb_filename }}"
    regexp: "^(#)?install usb-storage(\\s|$)"
    line: "install usb-storage /bin/true"
    state: present
    create: yes
  register: task04
  when: is_remediate

- name: 1.1.23|Disable USB Storage 
  moveit:
    section: 1.1.23
    description: Disable USB Storage - modprobe
    info: |
      <pre class="primary">
      Edit or create the file /etc/modprobe.d/usb-storage.conf and add the following line:
      </pre>
      <pre class="secondary">
      install usb-storage /bin/true
      </pre>
      <pre class="primary">
      Run the following command to unload the usb-storage module:
      </pre>
      <pre class="secondary">
      # rmmod usb-storage
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      {% if not task03.stat.exists %}
      touch /etc/modprobe.d/usb-storage.conf
      {% endif %}
      echo "install usb-storage /bin/true" >> "/etc/modprobe.d/usb-storage.conf"
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'changed' if task04.changed else 'passed' }}"
  when: is_remediate
  tags:
    - scored
    - Level1_Server
    - Level2_Workstation

- name: 1.1.23|task05
  modprobe:
    name: usb-storage
    state: absent
  register: task05
  when: is_remediate

- name: 1.1.23|Disable USB Storage
  moveit:
    section: 1.1.23
    description: Disable USB Storaged - lsmod
    info: |
      <pre class="primary">
      Edit or create the file /etc/modprobe.d/usb-storage.conf and add the following line:
      </pre>
      <pre class="secondary">
      install usb-storage /bin/true
      </pre>
      <pre class="primary">
      Run the following command to unload the usb-storage module:
      </pre>
      <pre class="secondary">
      # rmmod usb-storage
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      # rmmod usb-storage
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'changed' if task05.changed else 'passed' }}"
  when: is_remediate
  tags:
    - scored
    - Level1_Server
    - Level2_Workstation