---
#SB
- name: 1.1.6|Ensure separate partition exists for /var
  set_fact:
    var_exist: "{{ '/var' in  mountpoints }}"
  tags:
    - SET_FACT
    
- name: 1.1.6|Ensure separate partition exists for /var
  debug:
    msg: |
      {% if var_exist %}
        OK
      {% else %}
        Manually task
      {% endif %}
  changed_when: not var_exist
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation
    - RULE    
    - MANUAL