---
- name: 1.1.14|task01
  set_fact:
    home_partition_opt: "{{ home_partition_opt + ['nodev'] }}"
  when: is_compliance or is_remediate

- name: 1.1.14|task02
  set_fact:
    nodev_exist_in_home: "{{ 'nodev' in home_mountpoint_options }}"
  when: is_compliance or is_remediate

###############
#    Audit    #
###############

- name: 1.1.14|task03
  shell: /usr/bin/mount | /usr/bin/grep 'on /home ' | /usr/bin/awk '{print} END {if (NR == 0) print "failed"}'
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task03
  when: is_compliance

- name: 1.1.14|Ensure nodev option set on /home partition
  moveit:
    section: 1.1.14
    description: Ensure nodev option set on /home partition
    info: |
      <pre class="primary">
      If a /home partition exists run the following command and verify that the nodev option is set on /home:
      </pre>
      <pre class="secondary">
      # mount | grep /home
      tmpfs on /home type tmpfs (rw,nosuid,nodev,noexec,relatime)
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      mount | grep 'on /home '
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task03.stdout_lines | difference(["failed"]) | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'passed' if nodev_exist_in_home else 'failed' }}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation

###############
# Remediation #
###############

- name: 1.1.14|task04
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(home_partition_opt) | join(',') }}"
  when:
    - is_remediate
    - not nodev_exist_in_home
    - (item.mount == '/home')
  with_items: "{{ home_mountpoints }}"
  register: task04

- name: 1.1.14|Ensure nodev option set on /home partition
  moveit:
    section: 1.1.14
    description: Ensure nodev option set on /home partition
    info: |
      <pre class="primary">
      Edit the /etc/fstab file and add nodev to the fourth field (mounting options) for the /home partition. See the fstab(5) manual page for more information.
      </pre>
      <pre class="secondary">
      # mount -o remount,nodev /home
      </pre>
    cmd_output: |
      {% if not task04.changed %}
      <pre class="primary">Manual intervention required for partition-related controls.</pre>
      {% endif %}
    isRemediate: "{{ is_remediate }}"
    state: "{% if nodev_exist_in_home %}passed{% elif task04.changed %}changed{% else %}manual{% endif %}"
  when: is_remediate
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation