---

- name: 1.1.3|task01
  set_fact:
    tmp_partition_opt: "{{ tmp_partition_opt + ['nodev'] }}"
  when: is_compliance or is_remediate

- name: 1.1.3|task02
  set_fact:
    nodev_exist_in_tmp: "{{ 'nodev' in tmp_mountpoint_options }}"
  when: is_compliance or is_remediate

###############
#    Audit    #
###############

- name: 1.1.3|task03
  shell: /usr/bin/mount | /usr/bin/grep 'on /tmp ' | /usr/bin/awk '{print} END {if (NR == 0) print "failed"}'
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task03
  when: is_compliance

- name: 1.1.3|Ensure nodev option set on /tmp partition
  moveit:
    section: 1.1.3
    description: Ensure nodev option set on /tmp partition
    info: |
      <pre class="primary">
      If a /tmp partition exists run the following command and verify that the nodev option is set on /tmp:
      </pre>
      <pre class="secondary">
      # mount | grep /tmp
      tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noexec,relatime)
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      mount | grep 'on /tmp '
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task03.stdout_lines | difference(["failed"]) | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'passed' if nodev_exist_in_tmp else 'failed' }}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation

###############
# Remediation #
###############

- name: 1.1.3|task04
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(tmp_partition_opt) | join(',') }}"
  when:
    - is_remediate
    - not nodev_exist_in_tmp
    - (item.mount == '/tmp')
  with_items: "{{ tmp_mountpoints }}"
  register: task04

- name: 1.1.3|Ensure nodev option set on /tmp partition
  moveit:
    section: 1.1.3
    description: Ensure nodev option set on /tmp partition
    info: |
      <pre class="primary">
      Edit /etc/systemd/system/local-fs.target.wants/tmp.mount to add nodev to the /tmp mount options:
      </pre>
      <pre class="secondary">
      [Mount]
      Options=mode=1777,strictatime,noexec,nodev,nosuid
      </pre>
      <pre class="primary">
      Run the following command to remount /tmp :
      </pre>
      <pre class="secondary">
      # mount -o remount,nodev /tmp
      </pre>
    cmd_output: |
      {% if not task04.changed %}
      <pre class="primary">Manual intervention required for partition-related controls.</pre>
      {% endif %}
    isRemediate: "{{ is_remediate }}"
    state: "{% if nodev_exist_in_tmp %}passed{% elif task04.changed %}changed{% else %}manual{% endif %}"
  when: is_remediate
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation