---

- name: 1.1.13|task01
  set_fact:
    home_exist: "{{ '/home' in  mountpoints }}"
  when: is_compliance or is_remediate

###############
#    Audit    #
###############

- name: 1.1.13|task02
  shell: /usr/bin/mount | /usr/bin/grep 'on /home ' | /usr/bin/awk '{print} END {if (NR == 0) print "failed"}'
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task02
  when: is_compliance

- name: 1.1.13|Ensure separate partition exists for /home
  moveit:
    section: 1.1.13
    description: Ensure separate partition exists for /home
    info: |
      <pre class="primary">
      Run the following command and verify output shows /home is mounted:
      </pre>
      <pre class="secondary">
      # mount | grep /home
      /dev/xvdf1 on /home type ext4 (rw, nodev, relatime, data=ordered)
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      mount | grep 'on /home '
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task02.stdout_lines | difference(["failed"]) | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'passed' if home_exist else 'failed' }}"
  when: is_compliance
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation

###############
# Remediation #
###############

- name: 1.1.13|Ensure separate partition exists for /home
  moveit:
    section: 1.1.13
    description: Ensure separate partition exists for /home
    info: |
      <pre class="primary">
      For new installations, during installation create a custom partition setup and specify a separate partition for /home.
      For systems that were previously installed, create a new partition and configure /etc/fstab as appropriate.
      </pre>
    cmd_output: <pre class="primary">Manual intervention required for partition-related controls.</pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'passed' if home_exist else 'manual' }}"
  when: is_remediate
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation