---
#SB
- name: 1.2.2|task01
  shell: /usr/bin/systemctl is-enabled rhnsd 2> /dev/null | /usr/bin/egrep "disabled" | /usr/bin/awk '{print} END {if(NR==0) print "failed" }'
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task01
  when: is_compliance

###############
#    Audit    #
###############

- name: 1.2.2|Disable the rhnsd Daemon
  moveit:
    section: 1.2.2
    description: Disable the rhnsd Daemon
    info: |
      <pre class="primary">
      Run the following command and verify the rhnsd service is disabled
      </pre>
      <pre class="secondary">
      # systemctl is-enabled rhnsd
      disabled
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      # systemctl is-enabled rhnsd
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task01.stdout_lines | difference(["failed"]) | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'failed' if 'failed' in task01.stdout_lines else 'passed'}}"
  when: is_compliance
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation

###############
# Remediation #
###############

- name: 1.2.2|task02
  service:
    name: rhnsd
    state: stopped
    enabled: no
  when: is_remediate
  register: task02

- name: 1.2.2|Disable the rhnsd Daemon
  moveit:
    section: 1.2.2
    description: Disable the rhnsd Daemon
    info: |
      <pre class="primary">
      Run the following command to disable rhnsd :
      </pre>
      <pre class="secondary">
      # systemctl --now disable rhnsd
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      # systemctl --now disable rhnsd
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'changed' if task02.changed else 'passed'}}"
  when: is_remediate
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation