---
# SB
# VERIFY
###############
#    Audit    #
###############

- name: 1.3.1|task01
  shell: rpm -q sudo
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task01
  when: is_compliance

- name: 1.3.1|task02
  yum:
    name: sudo
    state: present
  register: task02
  when: is_compliance or is_remediate

- name: 1.3.1|Ensure SUDO is installed
  moveit:
    section: 1.3.1
    description: Ensure SUDO is installed
    info: |
      <pre class="primary">
      Run the following command and verify sudo is installed:
      </pre>
      <pre class="secondary">
      # rpm -q sudo
      sudo-&lt;version&gt;
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      rpm -q sudo
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task01.stdout_lines | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'failed' if task02.changed else 'passed'}}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation

###############
# Remediation #
###############

- name: 1.3.1|Ensure SUDO is installed
  moveit:
    section: 1.3.1
    description: Ensure SUDO is installed
    info: |
      <pre class="primary">
      Run the following command to install sudo :
      </pre>
      <pre class="secondary">
      # dnf install sudo
      </pre>

    cmd_output: |
      {% if task02.changed %}
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      # dnf install sudo
      </pre>
      {% endif %}

      {% if item.changed %}
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      {{item.cmd}}
      </pre>
      {% endif %}
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'changed' if task02.changed or task04.changed else 'passed'}}"
  when: is_remediate
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation