---

###############
#    Audit    #
###############

- name: 1.5.3|task01
  shell: /usr/bin/grep /systemd-sulogin-shell /usr/lib/systemd/system/rescue.service | /usr/bin/awk '{print} END {if (NR == 0) print "failed"}'
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task01
  when: is_compliance

- name: 1.5.3|Ensure authentication required for single user mode
  moveit:
    section: 1.5.3
    description: Ensure authentication required for single user mode - rescue.service
    info: |
      <pre class="primary">
      Run the following commands and verify that /systemd-sulogin-shell or /usr/systemd-sulogin-shell is used as shown:
      </pre>
      <pre class="secondary">
      # grep /systemd-sulogin-shell /usr/lib/systemd/system/rescue.service
      ExecStart=-/usr/lib/systemd/systemd-sulogin-shell rescue
      # grep /systemd-sulogin-shell /usr/lib/systemd/system/emergency.service
      ExecStart=-/usr/lib/systemd/systemd-sulogin-shell emergency
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      grep /systemd-sulogin-shell /usr/lib/systemd/system/rescue.service
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task01.stdout_lines | difference(["failed"]) | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'failed' if 'failed' in task01.stdout_lines else 'passed' }}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation

- name: 1.5.3|task02
  shell: /usr/bin/grep /systemd-sulogin-shell /usr/lib/systemd/system/emergency.service | /usr/bin/awk '{print} END {if (NR == 0) print "failed"}'
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task02
  when: is_compliance

- name: 1.5.3|Ensure authentication required for single user mode
  moveit:
    section: 1.5.3
    description: Ensure authentication required for single user mode - emergency.service
    info: |
      <pre class="primary">
      Run the following commands and verify that /systemd-sulogin-shell or /usr/systemd-sulogin-shell is used as shown:
      </pre>
      <pre class="secondary">
      # grep /systemd-sulogin-shell /usr/lib/systemd/system/rescue.service
      ExecStart=-/usr/lib/systemd/systemd-sulogin-shell rescue
      # grep /systemd-sulogin-shell /usr/lib/systemd/system/emergency.service
      ExecStart=-/usr/lib/systemd/systemd-sulogin-shell emergency
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      grep /systemd-sulogin-shell /usr/lib/systemd/system/emergency.service
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task02.stdout_lines | difference(["failed"]) | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'failed' if 'failed' in task02.stdout_lines else 'passed'}}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation

###############
# Remediation #
###############

- name: 1.5.3|task03
  lineinfile:
    path: /usr/lib/systemd/system/emergency.service
    regexp: "/sbin/sulogin"
    line: 'ExecStart=-/usr/lib/systemd/systemd-sulogin-shell emergency'
  when: is_remediate
  register: task03

- name: 1.5.3|task04
  lineinfile:
    path: /usr/lib/systemd/system/rescue.service
    regexp: "/sbin/sulogin"
    line: 'ExecStart=-/usr/lib/systemd/systemd-sulogin-shell rescue'
  when: is_remediate
  register: task04

- name: 1.5.3|Ensure authentication required for single user mode
  moveit:
    section: 1.5.3
    description: Ensure authentication required for single user mode - rescue.service
    info: |
      <pre class="primary">
      Edit /usr/lib/systemd/system/rescue.service and add the following:
      </pre>
      <pre class="secondary">
      # ExecStart=-/usr/lib/systemd/systemd-sulogin-shell rescue
      </pre>
    cmd_output: |
      <pre class="primary">
      Following line added to /usr/lib/systemd/system/rescue.service
      </pre>
      <pre class="secondary">
      ExecStart=-/usr/lib/systemd/systemd-sulogin-shell rescue
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'changed' if task04.changed else 'passed'}}"
  when: is_remediate
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation

- name: 1.5.3|Ensure authentication required for single user mode
  moveit:
    section: 1.5.3
    description: Ensure authentication required for single user mode - emergency.service
    info: |
      <pre class="primary">
      Edit /usr/lib/systemd/system/emergency.service and add the following:
      </pre>
      <pre class="secondary">
      # ExecStart=-/usr/lib/systemd/systemd-sulogin-shell emergency
      </pre>
    cmd_output: |
      <pre class="primary">
      Following line added to /usr/lib/systemd/system/emergency.service
      </pre>
      <pre class="secondary">
      ExecStart=-/usr/lib/systemd/systemd-sulogin-shell emergency
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'changed' if task03.changed else 'passed'}}"
  when: is_remediate
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation