---
#SB
###############
#    Audit    #
###############

- name: 1.7.1.7|task01
  shell: rpm -q mcstrans
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task01
  when: is_compliance

- name: 1.7.1.7|task02
  set_fact:
    is_installed: '{{ not task01.stdout is regex("not installed") }}'
  when: is_compliance

- name: 1.7.1.7|Ensure the MCS Translation Service (mcstrans) is not installed
  moveit:
    section: 1.7.1.7
    description: Ensure the MCS Translation Service (mcstrans) is not installed
    info: |
      <pre class="primary">
      Run the following command and verify mcstrans is not installed:
      </pre>
      <pre class="secondary">
      # rpm -q mcstrans
      package mcstrans is not installed
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      rpm -q mcstrans
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task01.stdout_lines | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'failed' if is_installed else 'passed' }}"
  when: is_compliance
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation

###############
# Remediation #
###############

- name: 1.7.1.7|task03
  yum:
    name: mcstrans
    state: absent
  register: task03
  when: is_remediate

- name: 1.7.1.7|Ensure the MCS Translation Service (mcstrans) is not installed
  moveit:
    section: 1.7.1.7
    description: Ensure the MCS Translation Service (mcstrans) is not installed
    info: |
      <pre class="primary">
      Run the following command to uninstall s etroubleshoot :
      </pre>
      <pre class="secondary">
      # dnf remove mcstrans
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      dnf remove mcstrans
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'changed' if task03.changed else 'passed' }}"
  when: is_remediate
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation