---

###############
#    Audit    #
###############

- name: 1.7.1.3|task01
  shell: cat /etc/issue.net
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: audit_1
  when: is_compliance

- name: 1.7.1.3|Ensure remote login warning banner is configured properly
  moveit:
    section: 1.7.1.3
    description: Ensure remote login warning banner is configured properly
    info: |
      <pre class="primary">
      Run the following command and verify that the contents match site policy:
      </pre>
      <pre class="secondary">
      # cat /etc/issue.net
      </pre>
      <pre class="primary">
      Run the following command and verify no results are returned:
      </pre>
      <pre class="secondary">
      # egrep '(\\v|\\r|\\m|\\s)' /etc/issue.net
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      cat /etc/issue.net
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ audit_1.stdout_lines | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'passed' if audit_1.stdout_lines|length > 0 else 'failed' }}"
  when: is_compliance
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation

- name: 1.7.1.3|task02
  shell: egrep '(\\v|\\r|\\m|\\s)' /etc/issue.net | /usr/bin/awk '{print} END {if (NR == 0) print "passed"}'
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: audit_2
  when: is_compliance

- name: 1.7.1.3|task03
  template:
    src: etc/issue.net.j2
    dest: /etc/issue.net
  register: remediate_1
  when: is_remediate or is_compliance

- name: 1.7.1.3|Ensure remote login warning banner is configured properly
  moveit:
    section: 1.7.1.3
    description: Ensure remote login warning banner is configured properly
    info: |
      <pre class="primary">
      Run the following command and verify that the contents match site policy:
      </pre>
      <pre class="secondary">
      # cat /etc/issue.net
      </pre>
      <pre class="primary">
      Run the following command and verify no results are returned:
      </pre>
      <pre class="secondary">
      # egrep '(\\v|\\r|\\m|\\s)' /etc/issue.net
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      egrep '(\\v|\\r|\\m|\\s)' /etc/issue.net
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ audit_2.stdout_lines | difference(["passed"]) | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'failed' if 'passed' not in audit_2.stdout_lines or remediate_1.changed else 'passed' }}"
  when: is_compliance
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation

###############
# Remediation #
###############

- name: 1.7.1.3|Ensure remote login warning banner is configured properly
  moveit:
    section: 1.7.1.3
    description: Ensure remote login warning banner is configured properly
    info: |
      <pre class="primary">
      Edit the /etc/issue.net file with the appropriate contents according to your site policy, remove any instances of \m , \r , \s , or \v.
      </pre>
    cmd_output: |
      <pre class="primary">
      /etc/issue.net file is changed
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'changed' if remediate_1.changed else 'passed' }}"
  when: is_remediate
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation