---
#SB
#VERIFY - DELETE the first section in audit and remediate
###############
#    Audit    #
###############

- name: 1.8.2|task01
  shell: systemctl show gdm | grep LoadState | cut -d = -f 2
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task01
  when: is_compliance or is_remediate

- name: 1.8.2|task02
  shell: (cat /etc/dconf/profile/gdm) | egrep "^\s*user-db\s*:\s*"
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task02
  when: is_compliance

- name: 1.8.2|task03
  set_fact:
    is_valid01: '{{ task02.stdout_lines is regex("^\s*user-db\s*:\s*user\s*$") }}'
  when: is_compliance

- name: 1.8.2|Ensure GDM login banner is configured
  moveit:
    section: 1.8.2
    description: Ensure GDM login banner is configured
    info: |
      <pre class="primary">
      If GDM is installed on the system verify that /etc/dconf/profile/gdm exists and contains the following
      </pre>
      <pre class="secondary">
      user-db:user
      system-db:gdm
      file-db:/usr/share/gdm/greeter-dconf-defaults
      </pre>
      <pre class="primary">
      Then verify the banner-message-enable and banner-message-text options are configured in one of the files in the /etc/gdm3/greeter.dconf-defaults directory:
      </pre>
      <pre class="secondary">
      [org/gnome/login-screen]
      banner-message-enable=true
      banner-message-text='&lt;banner message&gt;'
      </pre>
      <pre class="primary">
      This is typically configured in /etc/gdm3/greeter.dconf-defaults01-banner-message.
      </pre>
    cmd_output: |
      {% if task01.stdout == 'not-found' %}
      <pre class="primary">
      Package GDM is not installed
      </pre>
      {% else %}
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      # (cat /etc/dconf/profile/gdm) | egrep "^\s*user-db\s*:\s*"
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task02.stdout_lines | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
      {% endif %}
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'passed' if (task01.stdout == 'not-found') or (task01.stdout == 'loaded' and is_valid01) else 'failed'}}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation

- name: 1.8.2|task04
  shell: (cat /etc/dconf/profile/gdm) | egrep "^\s*system-db\s*:\s*"
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task04
  when: is_compliance

- name: 1.8.2|task05
  set_fact:
    is_valid02: '{{ task04.stdout_lines is regex("^\s*system-db\s*:\s*gdm\s*$d") }}'
  when: is_compliance

- name: 1.8.2|Ensure GDM login banner is configured
  moveit:
    section: 1.8.2
    description: Ensure GDM login banner is configured
    info: |
      <pre class="primary">
      If GDM is installed on the system verify that /etc/dconf/profile/gdm exists and contains the following
      </pre>
      <pre class="secondary">
      user-db:user
      system-db:gdm
      file-db:/usr/share/gdm/greeter-dconf-defaults
      </pre>
      <pre class="primary">
      Then verify the banner-message-enable and banner-message-text options are configured in one of the files in the /etc/gdm3/greeter.dconf-defaults directory:
      </pre>
      <pre class="secondary">
      [org/gnome/login-screen]
      banner-message-enable=true
      banner-message-text='&lt;banner message&gt;'
      </pre>
      <pre class="primary">
      This is typically configured in /etc/gdm3/greeter.dconf-defaults01-banner-message.
      </pre>
    cmd_output: |
      {% if task01.stdout == 'not-found' %}
      <pre class="primary">Package GDM is not installed</pre>
      {% else %}
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      # (cat /etc/dconf/profile/gdm) | egrep "^\s*system-db\s*:\s*"
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task04.stdout_lines | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
      {% endif %}
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'passed' if (task01.stdout == 'not-found') or (task01.stdout == 'loaded' and is_valid02) else 'failed'}}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation

- name: 1.8.2|task06
  shell: (cat /etc/dconf/profile/gdm) | egrep "^\s*file-db\s*:\s*"
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task06
  when: is_compliance

- name: 1.8.2|task07
  set_fact:
    is_valid03: '{{ task06.stdout_lines is regex("^\s*file-db\s*:\s*/usr/share/gdm/greeter-dconf-defaults\s*$") }}'
  when: is_compliance

- name: 1.8.2|Ensure GDM login banner is configured
  moveit:
    section: 1.8.2
    description: Ensure GDM login banner is configured
    info: |
      <pre class="primary">
      If GDM is installed on the system verify that /etc/dconf/profile/gdm exists and contains the following
      </pre>
      <pre class="secondary">
      user-db:user
      system-db:gdm
      file-db:/usr/share/gdm/greeter-dconf-defaults
      </pre>
      <pre class="primary">
      Then verify the banner-message-enable and banner-message-text options are configured in one of the files in the /etc/gdm3/greeter.dconf-defaults directory:
      </pre>
      <pre class="secondary">
      [org/gnome/login-screen]
      banner-message-enable=true
      banner-message-text='&lt;banner message&gt;'
      </pre>
      <pre class="primary">
      This is typically configured in /etc/gdm3/greeter.dconf-defaults01-banner-message.
      </pre>
    cmd_output: |
      {% if task01.stdout == 'not-found' %}
      <pre class="primary">Package GDM is not installed</pre>
      {% else %}
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      # (cat /etc/dconf/profile/gdm) | egrep "^\s*file-db\s*"
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task06.stdout_lines | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
      {% endif %}
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'passed' if (task01.stdout == 'not-found') or (task01.stdout == 'loaded' and is_valid03) else 'failed'}}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation


- name: 1.8.2|task08
  shell: (cat /etc/gdm3/greeter.dconf-defaults*) | egrep "^\s*banner-message-enable\s*="
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task08
  when: is_compliance

- name: 1.8.2|task09
  set_fact:
    is_valid04: '{{ task08.stdout_lines is regex("^\s*banner-message-enable\s*=\s*true\s*$") }}'
  when: is_compliance

- name: 1.8.2|Ensure GDM login banner is configured
  moveit:
    section: 1.8.2
    description: Ensure GDM login banner is configured
    info: |
      <pre class="primary">
      If GDM is installed on the system verify that /etc/dconf/profile/gdm exists and contains the following
      </pre>
      <pre class="secondary">
      user-db:user
      system-db:gdm
      file-db:/usr/share/gdm/greeter-dconf-defaults
      </pre>
      <pre class="primary">
      Then verify the banner-message-enable and banner-message-text options are configured in one of the files in the /etc/gdm3/greeter.dconf-defaults directory:
      </pre>
      <pre class="secondary">
      [org/gnome/login-screen]
      banner-message-enable=true
      banner-message-text='&lt;banner message&gt;'
      </pre>
      <pre class="primary">
      This is typically configured in /etc/gdm3/greeter.dconf-defaults01-banner-message.
      </pre>
    cmd_output: |
      {% if task01.stdout == 'not-found' %}
      <pre class="primary">Package GDM is not installed</pre>
      {% else %}
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      # (cat /etc/gdm3/greeter.dconf-defaults*) | egrep "^\s*banner-message-enable\s*="
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task08.stdout_lines | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
      {% endif %}
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'passed' if (task01.stdout == 'not-found') or (task01.stdout == 'loaded' and is_valid04) else 'failed'}}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation

- name: 1.8.2|task10
  shell: (cat /etc/gdm3/greeter.dconf-defaults*) | egrep "^\s*banner-message-text\s*="
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task10
  when: is_compliance

- name: 1.8.2|task11
  set_fact:
    is_valid05: '{{ task10.stdout_lines is regex("^\s*banner-message-text\s*=.*Authorized.*$") }}'
  when: is_compliance

- name: 1.8.2|Ensure GDM login banner is configured
  moveit:
    section: 1.8.2
    description: Ensure GDM login banner is configured
    info: |
      <pre class="primary">
      If GDM is installed on the system verify that /etc/dconf/profile/gdm exists and contains the following
      </pre>
      <pre class="secondary">
      user-db:user
      system-db:gdm
      file-db:/usr/share/gdm/greeter-dconf-defaults
      </pre>
      <pre class="primary">
      Then verify the banner-message-enable and banner-message-text options are configured in one of the files in the /etc/gdm3/greeter.dconf-defaults directory:
      </pre>
      <pre class="secondary">
      [org/gnome/login-screen]
      banner-message-enable=true
      banner-message-text='&lt;banner message&gt;'
      </pre>
      <pre class="primary">
      This is typically configured in /etc/gdm3/greeter.dconf-defaults01-banner-message.
      </pre>
    cmd_output: |
      {% if task01.stdout == 'not-found' %}
      <pre class="primary">Package GDM is not installed</pre>
      {% else %}
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      # (cat /etc/gdm3/greeter.dconf-defaults*) | egrep "^\s*banner-message-text\s*="
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task10.stdout_lines | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
      {% endif %}
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'passed' if (task01.stdout == 'not-found') or (task01.stdout == 'loaded' and is_valid05) else 'failed'}}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation

###############
# Remediation #
###############

- name: 1.8.2|task12
  lineinfile:
    path: "{{ item.file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644
  with_items:
    - { file: '/etc/dconf/profile/gdm', regexp: 'user-db', line: 'user-db:user' }
    - { file: '/etc/dconf/profile/gdm', regexp: 'system-db', line: 'system-db:gdm' }
    - { file: '/etc/dconf/profile/gdm', regexp: 'file-db', line: 'file-db:/usr/share/gdm/greeter-dconf-defaults' }
    - { file: '/etc/gdm3/greeter.dconf-defaults01-banner-message', regexp: '\[org\/gnome\/login-screen\]', line: '[org/gnome/login-screen]' }
    - { file: '/etc/gdm3/greeter.dconf-defaults01-banner-message', regexp: 'banner-message-enable', line: 'banner-message-enable=true' }
    - { file: '/etc/gdm3/greeter.dconf-defaults01-banner-message', regexp: 'banner-message-text', line: "banner-message-text='{{ cis_warning_banner }}'\n" }
  notify: reload dconf
  when: ('loaded' in task01.stdout)
  register: task12

- name: 1.8.2|Ensure GDM login banner is configured
  moveit:
    section: 1.8.2
    description: Ensure GDM login banner is configured
    info: |
      <pre class="primary">
      Create the /etc/dconf/profile/gdm file with the following contents:
      </pre>
      <pre class="secondary">
      user-db:user
      system-db:gdm
      file-db:/usr/share/gdm/greeter-dconf-defaults
      </pre>

      <pre class="primary">
      Create or edit the banner-message-enable and banner-message-text options in /etc/gdm3/greeter.dconf-defaults01-banner-message:
      </pre>
      <pre class="secondary">
      [org/gnome/login-screen]
      banner-message-enable=true
      banner-message-text='Authorized uses only. All activity may be monitored and reported.'
      </pre>

      <pre class="primary">
      Run the following command to update the system databases:
      </pre>
      <pre class="secondary">
      # dconf update
      </pre>
    cmd_output: |
      {% if task01.stdout == 'not-found' %}
      <pre class="primary">
      Package GDM is not installed
      </pre>
      {% endif %}

      <pre class="primary">Following files modified:
      </pre>
      <pre class="secondary">
      - /etc/dconf/profile/gdm
      - /etc/gdm3/greeter.dconf-defaults01-banner-message
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'changed' if task12.changed else 'passed'}}"
  when: is_remediate
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation