---

- name: 2.1.7|Ensure xinetd is not enabled
  service:
    name: xinetd
    enabled: no
    state: stopped
  when: xinetd_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE