---

- name: 2.1.1|Ensure chargen services are not enabled
  stat:
    path: /etc/xinetd.d/chargen-dgram
  register: task_2_1_1_a
  changed_when: no
  tags:
    - PRE_TASK

- name: 2.1.1|Ensure chargen services are not enabled
  shell: chkconfig --list chargen-dgram 2>/dev/null | grep -q "on" && echo "True" || echo "False"
  when: task_2_1_1_a.stat.exists
  register: task_2_1_1_b
  changed_when: task_2_1_1_b.stdout == "True"
  check_mode: no
  tags:
    - PRE_TASK

- name: 2.1.1|Ensure chargen services are not enabled
  shell: chkconfig chargen-dgram off
  notify: restart xinetd
  when: 
    - task_2_1_1_a.stat.exists
    - task_2_1_1_b.stdout == "True"
  check_mode: no
  changed_when: no    
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE

- name: 2.1.1|Ensure chargen services are not enabled
  stat:
    path: /etc/xinetd.d/chargen-stream
  register: task_2_1_1_c
  changed_when: no
  tags:
    - PRE_TASK
    
- name: 2.1.1|Ensure chargen services are not enabled
  shell: chkconfig --list chargen-stream 2>/dev/null | grep -q "on" && echo "True" || echo "False"
  when: task_2_1_1_c.stat.exists
  register: task_2_1_1_d
  changed_when: task_2_1_1_d.stdout == "True"
  check_mode: no
  tags:
    - PRE_TASK

- name: 2.1.1|Ensure chargen services are not enabled
  shell: chkconfig chargen-stream off
  notify: restart xinetd
  when: 
    - task_2_1_1_c.stat.exists
    - task_2_1_1_d.stdout == "True"
  check_mode: no
  changed_when: no    
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE