---

- name: 2.1.5|Ensure time services are not enabled
  stat:
    path: /etc/xinetd.d/time-dgram
  register: task_2_1_5_a
  changed_when: no
  tags:
    - PRE_TASK

- name: 2.1.5|Ensure time services are not enabled
  shell: chkconfig --list time-dgram 2>/dev/null | grep -q "on" && echo "True" || echo "False"
  when: task_2_1_5_a.stat.exists
  register: task_2_1_5_b
  changed_when: task_2_1_5_b.stdout == "True"
  check_mode: no
  tags:
    - PRE_TASK

- name: 2.1.5|Ensure time services are not enabled
  shell: chkconfig time-dgram off
  notify: restart xinetd
  when: 
    - task_2_1_5_a.stat.exists
    - task_2_1_5_b.stdout == "True"
  check_mode: no
  changed_when: no    
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE  
  
- name: 2.1.5|Ensure time services are not enabled
  stat:
    path: /etc/xinetd.d/time-stream
  register: task_2_1_5_c
  changed_when: no
  tags:
    - PRE_TASK
    
- name: 2.1.5|Ensure time services are not enabled
  shell: chkconfig --list time-stream 2>/dev/null | grep -q "on" && echo "True" || echo "False"
  when: task_2_1_5_c.stat.exists
  register: task_2_1_5_d
  changed_when: task_2_1_5_d.stdout == "True"
  check_mode: no
  tags:
    - PRE_TASK

- name: 2.1.5|Ensure time services are not enabled
  shell: chkconfig time-stream off
  notify: restart xinetd
  when: 
    - task_2_1_5_c.stat.exists
    - task_2_1_5_d.stdout == "True"
  check_mode: no
  changed_when: no    
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE