---

- name: 2.1.4|Ensure echo services are not enabled 
  stat:
    path: /etc/xinetd.d/echo-dgram
  register: task_2_1_4_a
  changed_when: no
  tags:
    - PRE_TASK

- name: 2.1.4|Ensure echo services are not enabled 
  shell: chkconfig --list echo-dgram 2>/dev/null | grep -q "on" && echo "True" || echo "False"
  when: task_2_1_4_a.stat.exists
  register: task_2_1_4_b
  changed_when: task_2_1_4_b.stdout == "True"
  check_mode: no
  tags:
    - PRE_TASK

- name: 2.1.4|Ensure echo services are not enabled 
  shell: chkconfig echo-dgram off
  notify: restart xinetd
  when: 
    - task_2_1_4_a.stat.exists
    - task_2_1_4_b.stdout == "True"
  check_mode: no
  changed_when: no    
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE  
  
- name: 2.1.4|Ensure echo services are not enabled 
  stat:
    path: /etc/xinetd.d/echo-stream
  register: task_2_1_4_c
  changed_when: no
  tags:
    - PRE_TASK

- name: 2.1.4|Ensure echo services are not enabled 
  shell: chkconfig --list echo-stream 2>/dev/null | grep -q "on" && echo "True" || echo "False"
  when: task_2_1_4_c.stat.exists
  register: task_2_1_4_d
  changed_when: task_2_1_4_d.stdout == "True"
  check_mode: no
  tags:
    - PRE_TASK

- name: 2.1.4|Ensure echo services are not enabled 
  shell: chkconfig echo-stream off
  notify: restart xinetd
  check_mode: no
  changed_when: no  
  when: 
    - task_2_1_4_c.stat.exists
    - task_2_1_4_d.stdout == "True"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE