---

- name: 2.2.16|Ensure NIS Server is not enabled 
  service:
    name: ypserv
    state: stopped
    enabled: no     
  when: ypserv_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE