---

- name: 2.2.19|Ensure telnet server is not enabled 
  service:
    name: telnet.socket
    state: stopped
    enabled: no     
  when: telnet_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE