---

- name: 2.2.11|Ensure IMAP and POP3 server is not enabled 
  service:
    name: dovecot
    state: stopped
    enabled: no   
  when: dovecot_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE