---

- name: 2.2.20|Ensure tftp server is not enabled 
  service:
    name: tftp.socket
    state: stopped
    enabled: no     
  when: tftp_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE