---

- name: 2.2.17|Ensure rsh server is not enabled 
  service:
    name: rsh.socket
    enabled: no
    state: stopped
  when: rsh_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE

- name: 2.2.17|Ensure rsh server is not enabled 
  service:
    name: rlogin.socket
    enabled: no
    state: stopped
  when: rlogin_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE

- name: 2.2.17|Ensure rsh server is not enabled 
  service:
    name: rexec.socket
    enabled: no
    state: stopped
  when: rexec_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE    