---
    
- name: 2.2.7|Ensure NFS and RPC are not enabled 
  service:
    name: nfs
    enabled: no
    state: stopped
  when: nfs_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE        

- name: 2.2.7|Ensure NFS and RPC are not enabled 
  service:
    name: nfs-server
    enabled: no
    state: stopped
  when: nfs_server_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE   

- name: 2.2.7|Ensure NFS and RPC are not enabled 
  service:
    name: rpcbind
    enabled: no
    state: stopped
  when: rpcbind_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE           