---

- name: 2.2.5|Ensure DHCP Server is not enabled 
  service:
    name: dhcpd
    state: stopped
    enabled: no  
  when: dhcpd_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE