---

- name: 2.2.10|Ensure HTTP server is not enabled 
  service:
    name: httpd
    state: stopped
    enabled: no   
  when: httpd_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE