---

- name: 1.2.5|task01
  shell: /sbin/chkconfig --list rhnsd 2> /dev/null | /usr/bin/egrep "^\s*rhnsd.*0:off.*1:off.*2:off.*3:off.*4:off.*5:off.*6:off.*" | /usr/bin/awk '{print} END {if(NR==0) print "failed" }'
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task01
  when: is_compliance

###############
#    Audit    #
###############

- name: 1.2.5|Disable the rhnsd Daemon
  moveit:
    section: 1.2.5
    description: Disable the rhnsd Daemon
    info: |
      <pre class="primary">
      Run the following command and verify all runlevels are listed as "off" or rhnsd is not available:
      </pre>
      <pre class="secondary">
      # chkconfig --list rhnsd
      rhnsd 0:off 1:off 2:off 3:off 4:off 5:off 6:off
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      # chkconfig --list rhnsd
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task01.stdout_lines | difference(["failed"]) | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'failed' if 'failed' in task01.stdout_lines else 'passed'}}"
  when: is_compliance
  tags:
    - not_scored
    - Level2_Server
    - Level2_Workstation

###############
# Remediation #
###############

- name: 1.2.5|task02
  service:
    name: rhnsd
    state: stopped
    enabled: no
  when: is_remediate
  register: task02

- name: 1.2.5|Disable the rhnsd Daemon
  moveit:
    section: 1.2.5
    description: Disable the rhnsd Daemon
    info: |
      <pre class="primary">
      Run the following command to disable rhnsd :
      </pre>
      <pre class="secondary">
      # chkconfig rhnsd off
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      # chkconfig rhnsd off
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'changed' if task02.changed else 'passed'}}"
  when: is_remediate
  tags:
    - not_scored
    - Level2_Server
    - Level2_Workstation