---

###############
#    Audit    #
###############

- name: 1.3.2|task01
  shell: /usr/bin/crontab -u root -l; /usr/bin/grep -r aide /etc/cron.* /etc/crontab | egrep "[^#;]0 5 \* \* \* .* \/usr\/sbin\/aide --check" 2> /dev/null | /usr/bin/awk '{print} END {if (NR == 0) print "failed"}'
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task01
  when: is_compliance or is_remediate

- name: 1.3.2|task02
  set_fact:
    aide_check_exist: "{{ False if 'failed' in task01.stdout_lines else True }}"
  when: is_compliance or is_remediate

- name: 1.3.2|Ensure filesystem integrity is regularly checked
  moveit:
    section: 1.3.2
    description: Ensure filesystem integrity is regularly checked
    info: |
      <pre class="primary">
      Run the following commands to determine if there is a cron job scheduled to run the aide check.
      </pre>
      <pre class="secondary">
      # crontab -u root -l | grep aide
      # grep -r aide /etc/cron.* /etc/crontab
      </pre>
      <pre class="primary">
      Ensure a cron job in compliance with site policy is returned.
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      /usr/bin/crontab -u root -l; /usr/bin/grep -r aide /etc/cron.* /etc/crontab
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task01.stdout_lines | difference(["failed"]) | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'passed' if aide_check_exist else 'failed'}}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation

###############
# Remediation #
###############

- name: 1.3.2|task03
  yum:
    name: cronie
    state: present
  register: task03
  when: is_remediate

- name: 1.3.2|Ensure filesystem integrity is regularly checked
  cron:
    name: "CIS 1.3.2 - Run aide filesystem integrity check"
    cron_file : "{{ cis_aide_cron['file'] }}"
    user: "{{ cis_aide_cron['user'] }}"
    minute: "{{ cis_aide_cron['minute'] }}"
    hour: "{{ cis_aide_cron['hour'] }}"
    day: "{{ cis_aide_cron['dom'] }}"
    month: "{{ cis_aide_cron['month'] }}"
    weekday: "{{ cis_aide_cron['dow'] }}"
    job: "{{ cis_aide_cron['job'] }}"
    state: present
  register: task03
  when:
    - is_remediate
    - not aide_check_exist

- name: 1.3.2|Ensure filesystem integrity is regularly checked
  moveit:
    section: 1.3.2
    description: Ensure filesystem integrity is regularly checked
    info: |
      <pre class="primary">
      Run the following command:
      </pre>
      <pre class="secondary">
      # crontab -u root -e
      </pre>
      <pre class="primary">
      Add the following line to the crontab:
      </pre>
      <pre class="secondary">
      0 5 * * * /usr/sbin/aide --check
      </pre>
    cmd_output: |
      <pre class="primary">
      Following line added to {{ cis_aide_cron['file'] }}
      </pre>
      <pre class="secondary">
      0 5 * * * /usr/sbin/aide --check
      {{ cis_aide_cron['minute'] }} {{ cis_aide_cron['hour'] }} {{ cis_aide_cron['dom'] }} {{ cis_aide_cron['month'] }} {{ cis_aide_cron['dow'] }} {{ cis_aide_cron['dow'] }} {{ cis_aide_cron['job'] }}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'passed' if aide_check_exist else 'changed'}}"
  when: is_remediate
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation