---

###############
#    Audit    #
###############

- name: 1.5.2|task01
  shell: set -o pipefail && dmesg | grep -E "NX|XD" | /usr/bin/grep " active" | /usr/bin/awk '{print} END {if (NR == 0) print "failed"}'
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task01
  when: is_compliance or is_remediate

- name: 1.5.2|Ensure XD/NX support is enabled
  moveit:
    section: 1.5.2
    description: Ensure XD/NX support is enabled
    info: |
      <pre class="primary">
      Run the following command and verify your kernel has identified and activated NX/XD protection.
      </pre>
      <pre class="secondary">
      # dmesg | grep NX
      NX (Execute Disable) protection: active
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      dmesg | grep -E "NX|XD" | /usr/bin/grep " active"
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task01.stdout_lines | difference(["failed"]) | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'failed' if 'failed' in task01.stdout_lines else 'passed' }}"
  when: is_compliance
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation

###############
# Remediation #
###############

- name: 1.5.2|Ensure XD/NX support is enabled
  moveit:
    section: 1.5.2
    description: Ensure XD/NX support is enabled
    info: |
      <pre class="primary">
      On 32 bit systems install a kernel with PAE support, no installation is required on 64 bit systems:
      If necessary configure your bootloader to load the new kernel and reboot the system.
      You may need to enable NX or XD support in your bios.
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'manual' if 'failed' in task01.stdout_lines else 'passed' }}"
  when: is_remediate
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation