---

###############
#    Audit    #
###############

- name: 1.5.4|task01
  shell: rpm -q prelink
  args:
    warn: no
  check_mode: no
  changed_when: no
  failed_when: no
  register: task01
  when: is_compliance or is_remediate

- name: 1.5.4|task02
  set_fact:
    prelink_installed: '{{ not task01.stdout is regex("not installed") }}'
  when: is_compliance or is_remediate

- name: 1.5.4|Ensure prelink is disabled
  moveit:
    section: 1.5.4
    description: Ensure prelink is disabled
    info: |
      <pre class="primary">
      Run the following command and verify prelink is not installed:
      </pre>
      <pre class="secondary">
      # rpm -q prelink
      package prelink is not installed
      </pre>
    cmd_output: |
      <pre class="primary">
      <b>Command executed:</b>
      </pre>
      <pre class="secondary">
      rpm -q prelink
      </pre>
      <pre class="primary">
      <b>Output:</b>
      </pre>
      <pre class="secondary">
      {{ task01.stdout_lines | default(["&lt;no-output&gt;"], true) | join('<br>')}}
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'failed' if prelink_installed else 'passed' }}"
  when: is_compliance
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation

###############
# Remediation #
###############

- name: 1.5.4|task03
  shell: prelink -ua
  args:
    warn: no
  check_mode: no
  changed_when: yes
  failed_when: no
  register: task03
  when:
    - is_remediate
    - prelink_installed

- name: 1.5.4|task04
  yum:
    name: prelink
    state: absent
  register: task04
  when: is_remediate

- name: 1.5.4|Ensure prelink is disabled
  moveit:
    section: 1.5.4
    description: Ensure prelink is disabled
    info: |
      <pre class="primary">
      Run the following commands to restore binaries to normal and uninstall prelink :
      </pre>
      <pre class="secondary">
      # prelink -ua
      # yum remove prelink
      </pre>
    cmd_output: |
      <pre class="primary">
      Following commands executed
      </pre>
      <pre class="secondary">
      prelink -ua
      yum remove prelink
      </pre>
    isRemediate: "{{ is_remediate }}"
    state: "{{ 'changed' if task03.changed or task04.changed else 'passed' }}"
  when: is_remediate
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation