---

- name: 3.2.4|Ensure suspicious packets are logged 
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
  with_items:
      - { name: net.ipv4.conf.all.log_martians, value: 1 }
      - { name: net.ipv4.conf.default.log_martians, value: 1 }
  notify: sysctl flush ipv4 route table
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 