---

- name: 3.3.3|Ensure IPv6 is disabled 
  lineinfile:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=.*(?!.*ipv6\.disable=1)\"[^\"]+)(\".*)'
    line: '\1 ipv6.disable=1\2'
    backrefs: yes
  notify:
    - grub2cfg
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation
    - RULE     