---

- name: 3.4.2|Ensure /etc/hosts.allow is configured
  template:
    src: hosts.allow.j2
    dest: /etc/hosts.allow
    owner: root
    group: root
    mode: 0644
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 