---

- name: 3.5.2|Ensure SCTP is disabled 
  lineinfile:
    path: "{{ cis_modprobe_conf_filename }}"
    regexp: "^(#)?install sctp(\\s|$)"
    line: "install sctp /bin/true"
    create: yes
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation
    - RULE 