---

- name: 3.5.4|Ensure TIPC is disabled 
  lineinfile:
    path: "{{ cis_modprobe_conf_filename }}"
    regexp: "^(#)?install tipc(\\s|$)"
    line: "install tipc /bin/true"
    create: yes
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation
    - RULE   