---

- name: 3.5.3|Ensure RDS is disabled 
  lineinfile:
    path: "{{ cis_modprobe_conf_filename }}"
    regexp: "^(#)?install rds(\\s|$)"
    line: "install rds /bin/true"
    create: yes
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation
    - RULE 