---

- name: 3.6.3|Ensure loopback traffic is configured 
  debug:
    msg: "WARNING - This check has not been implemented yet."
  when: cis_firewall == "firewalld"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE   

- name: 3.6.3|Ensure loopback traffic is configured 
  iptables:
    chain: INPUT
    in_interface: "lo"
    jump: ACCEPT
    action: append
  when: cis_firewall == "iptables"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE

- name: 3.6.3|Ensure loopback traffic is configured 
  iptables:
    chain: OUTPUT
    out_interface: "lo"
    jump: ACCEPT
    action: append
  when: cis_firewall == "iptables"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE

- name: 3.6.3|Ensure loopback traffic is configured 
  iptables:
    chain: INPUT
    source: 127.0.0.0/8
    jump: DROP
    action: append
  when: cis_firewall == "iptables"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 