---

- name: 4.1.18|Ensure the audit configuration is immutable 
  template:
    src: audit/rhel7cis_rule_4_1_18.rules.j2
    dest: /etc/audit/rules.d/rhel7cis_rule_4_1_18.rules
    owner: root
    group: root
    mode: 0600
  notify: restart auditd
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation
    - RULE 