---

- name: 4.1.1.1|Ensure audit log storage size is configured 
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: "^max_log_file( |=)"
    line: "max_log_file = {{max_log_file_size}}"
    state: present
  notify: restart auditd
  tags:
    - not_scored
    - Level2_Server
    - Level2_Workstation
    - RULE  