---

- name: 4.1.12|Ensure use of privileged commands is collected 
  shell: >-
    set -o pipefail &&
      for i in $(df | grep '^/dev' | awk '{ print $NF }'); do
        find $i -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null;
    done
  register: rule_4_1_12
  changed_when: no
  check_mode: no
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.12

- name: 4.1.12|Ensure use of privileged commands is collected 
  template:
    src: audit/rhel7cis_rule_4_1_12.rules.j2
    dest: /etc/audit/rules.d/rhel7cis_rule_4_1_12.rules
    owner: root
    group: root
    mode: 0600
  notify: restart auditd
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation
    - RULE 