---

- name: 4.1.8|Ensure login and logout events are collected 
  template:
    src: audit/rhel7cis_rule_4_1_8.rules.j2
    dest: /etc/audit/rules.d/rhel7cis_rule_4_1_8.rules
    owner: root
    group: root
    mode: 0600
  notify: restart auditd
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation
    - RULE   