---

- name: 4.2.2.3|Ensure syslog-ng default file permissions configured 
  replace:
    path: /etc/syslog-ng/syslog-ng.conf
    regexp: '(?:(options \{)((?:.*?\r?\n?)*)\}\;)+'
    replace: 'options { chain_hostnames(off); flush_lines(0); perm(0640); stats_freq(3600); threaded(yes); };'
    backup: yes
  when: cis_enable_syslog_ng
  notify: restart syslog-ng
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE  