---

- name: 4.2.1.1|Ensure rsyslog Service is enabled 
  yum:
    name: rsyslog
    state: present
  when: cis_enable_rsyslog
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

# - name: 4.2.1.1|Ensure syslog-ng service is enabled 
#   shell: systemctl is-enabled rsyslog 2> /dev/null | grep -e 'enabled\|disabled' || echo 'error'
#   register: syslog_ng_4_2_1_1    

- name: 4.2.1.1|Ensure rsyslog Service is enabled 
  service:
    name: rsyslog
    enabled: yes
    state: started
  when: cis_enable_rsyslog
  # when: syslog_ng_4_2_1_1.stdout in ["enabled", "disabled"]
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE