---

- name: 6.1.14|Audit SGID executables 
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -2000
  register: task_6_1_14
  check_mode: no
  changed_when: no
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE 

- name: 6.1.14|Audit SGID executables 
  fail:
    msg: "{{ task_6_1_14.stdout }}"
  when:
    - task_6_1_14.stdout_lines is defined and task_6_1_14.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE 

- name: 6.1.14|Audit SGID executables 
  debug:
    msg: "{{ task_6_1_14.stdout }}"
  when:
    - task_6_1_14.stdout_lines is defined and task_6_1_14.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE 