---

- name: 6.1.1|Audit system file permissions
  shell: rpm -Va --nomtime --nosize --nomd5 --nolinkto
  register: task_6_1_1
  check_mode: no
  changed_when: no
  tags:
    - not_scored
    - Level2_Server
    - Level2_Workstation
    - RULE   

- name: 6.1.1|Audit system file permissions
  fail:
    msg: "{{ task_6_1_1.stdout_lines  | join('\n')}}"
  when:
    - task_6_1_1.stdout_lines is defined and task_6_1_1.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - not_scored
    - Level2_Server
    - Level2_Workstation
    - RULE   

- name: 6.1.1|Audit system file permissions
  debug:
    msg: "{{ task_6_1_1.stdout  | join('\n') }}"
  when:
    - task_6_1_1.stdout_lines is defined and task_6_1_1.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - not_scored
    - Level2_Server
    - Level2_Workstation
    - RULE 