---

- name: 6.1.8|Ensure permissions on /etc/group- are configured 
  file:
    dest: /etc/group-
    owner: root
    group: root
    mode: 0600
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE 