---

- name: 6.2.4|Ensure no legacy "+" entries exist in /etc/group 
  replace:
    dest: "/etc/group"
    regexp: "^\\+:.*\n"
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE     