---

- name: 6.2.3|Ensure no legacy "+" entries exist in /etc/shadow 
  replace:
    dest: "/etc/shadow"
    regexp: "^\\+:.*\n"
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE  