---

- name: 5.1.2|Ensure permissions on /etc/crontab are configured 
  file:
    dest: /etc/crontab
    owner: root
    group: root
    mode: 0600
  tags:    
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 