---

- name: 5.1.5|Ensure permissions on /etc/cron.weekly are configured 
  file:
    dest: /etc/cron.weekly
    state: directory
    owner: root
    group: root
    mode: 0700
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE  