---

## Some organizations may have stricter requirements for approved ciphers
# - name: "SCORED | 5.2.11 | PATCH | Ensure only approved ciphers are used"
#   lineinfile:
#       state: present
#       path: /etc/ssh/sshd_config
#       regexp: '(?i)^Ciphers\\s+'
#       line: "Ciphers {{ cis_sshd['ciphers'] }}"
#   notify: restart sshd 
#   tags:
#     - scored
#     - Level1_Server
#     - Level1_Workstation
#     - RULE 

- name: 5.2.11|Ensure only approved MAC algorithms are used 
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: "(?i)^(#)?MACs\\s+"
    line: "MACs {{ cis_sshd['macs'] }}"
  notify: restart sshd 
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE