---

- name: 5.2.1|Ensure permissions on /etc/ssh/sshd_config are configured 
  file:
    path: /etc/ssh/sshd_config
    state: file
    owner: root
    group: root
    mode: 0600
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE