---

- name: 5.2.10|Ensure SSH PermitUserEnvironment is disabled 
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: "(?i)^(#)?PermitUserEnvironment\\s+"
    line: 'PermitUserEnvironment no'
  notify: restart sshd 
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE