---

# system-auth
- name: 5.3.2|Ensure lockout for failed password attempts is configured 
  pamd:
    name: system-auth
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: required
    new_module_path: pam_faillock.so
    module_arguments: 
      - preauth
      - audit
      - silent
      - deny={{ cis_lockout['pwfailed_attempts']|trim }}
      - unlock_time={{ cis_lockout['pwunlock_time']|trim }}
    state: before
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

- name: 5.3.2|Ensure lockout for failed password attempts is configured 
  pamd:
    name: system-auth
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: sufficient
    new_module_path: pam_faillock.so
    module_arguments: 
      - authsucc
      - audit
      - deny={{ cis_lockout['pwfailed_attempts']|trim }}
      - unlock_time={{ cis_lockout['pwunlock_time']|trim }}
    state: after
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

- name: 5.3.2|Ensure lockout for failed password attempts is configured 
  pamd:
    name: system-auth
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: "[default=die]"
    new_module_path: pam_faillock.so
    module_arguments: 
      - authfail
      - audit 
      - deny={{ cis_lockout['pwfailed_attempts']|trim }}
      - unlock_time={{ cis_lockout['pwunlock_time']|trim }}
    state: after
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

- name: 5.3.2|Ensure lockout for failed password attempts is configured 
  pamd:
    name: system-auth
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_control: '[success=1 default=bad]'
    module_arguments: 'REMOVEME'
    state: updated
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

- name: 5.3.2|Ensure lockout for failed password attempts is configured
  replace:
    path: /etc/pam.d/system-auth
    regexp: 'REMOVEME'
    replace: ''        
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

# password-auth
- name: 5.3.2|Ensure lockout for failed password attempts is configured 
  pamd:
    name: password-auth
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: required
    new_module_path: pam_faillock.so
    module_arguments: 
      - preauth
      - audit
      - silent
      - deny={{ cis_lockout['pwfailed_attempts']|trim }}
      - unlock_time={{ cis_lockout['pwunlock_time']|trim }}
    state: before
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

- name: 5.3.2|Ensure lockout for failed password attempts is configured 
  pamd:
    name: password-auth
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: sufficient
    new_module_path: pam_faillock.so
    module_arguments: 
      - authsucc
      - audit
      - deny={{ cis_lockout['pwfailed_attempts']|trim }}
      - unlock_time={{ cis_lockout['pwunlock_time']|trim }}
    state: after
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

- name: 5.3.2|Ensure lockout for failed password attempts is configured 
  pamd:
    name: password-auth
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: "[default=die]"
    new_module_path: pam_faillock.so
    module_arguments: 
      - authfail
      - audit 
      - deny={{ cis_lockout['pwfailed_attempts']|trim }}
      - unlock_time={{ cis_lockout['pwunlock_time']|trim }}
    state: after
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

- name: 5.3.2|Ensure lockout for failed password attempts is configured 
  pamd:
    name: password-auth
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_control: '[success=1 default=bad]'
    module_arguments: 'REMOVEME'
    state: updated
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

- name: 5.3.2|Ensure lockout for failed password attempts is configured
  replace:
    path: /etc/pam.d/password-auth
    regexp: 'REMOVEME'
    replace: ''    
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 