---

- name: 5.4.1.4|Ensure inactive password lock is 30 days or less 
  lineinfile:
    state: present
    path: /etc/default/useradd
    regexp: "^INACTIVE\\s+"
    line: "INACTIVE={{ cis_pass['inactive_lock'] }}"
  register: task_5_4_1_4
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

- name: 5.4.1.4|Ensure inactive password lock is 30 days or less 
  shell: "chage --inactive {{ cis_pass['inactive_lock'] }} {{ item }}"
  with_items: "{{ task_5_4_1_1.stdout_lines|default([]) }}"
  check_mode: no
  changed_when: no
  register: task_5_4_1_4_b
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE  