---

- name: 5.4.4|Ensure default user umask is 027 or more restrictive 
  lineinfile:
    regexp: "^umask\\s+"
    line: "umask {{ cis_umask_default }}"
    path: "{{ item }}"
  with_items: "{{ cis_umask_shell_files }}"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE   