---

- name: 5.4.1.5|Ensure all users last password change date is in the past 
  script: audit_5.4.1.5.sh
  args: 
    executable: bash -l
  check_mode: no
  changed_when: 
    - audit_5_4_1_5.stdout_lines is defined 
    - audit_5_4_1_5.stdout_lines|length > 1
  register: audit_5_4_1_5
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE  

- name: 5.4.1.5|Ensure all users last password change date is in the past
  shell: "chage -d 0 {{ item }}"
  when: 
    - audit_5_4_1_5.stdout_lines is defined 
    - audit_5_4_1_5.stdout_lines|length > 1
    - item != ""
  with_items: "{{ audit_5_4_1_5.stdout_lines }}"
  register: task_5_4_1_5
  changed_when: task_5_4_1_5.changed
  check_mode: no  
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE  

- name: 5.4.1.5|Ensure all users last password change date is in the past
  debug:
    msg: "Password changed for user: {{ item.item }}"
  changed_when: task_5_4_1_5.changed
  when: 
    - task_5_4_1_5 is defined
    - item.item != ""
  with_items: "{{ task_5_4_1_5.results }}"


  
  