---

- name: 5.4.3|Ensure default group for the root account is GID 0 
  shell: usermod -g 0 root
  changed_when: no
  check_mode: no  
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 