---

- name: 5.4.1.1|Ensure password expiration is 365 days or less
  shell: "egrep ^[^:]+:[^\\!*] /etc/shadow | egrep -v '^({{ cis_ignore_user }})' | cut -d: -f1"
  register: task_5_4_1_1
  check_mode: no
  changed_when: no
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

- name: 5.4.1.1|Ensure password expiration is 365 days or less 
  lineinfile:
    state: present
    path: /etc/login.defs
    regexp: "^PASS_MAX_DAYS\\s+"
    line: "PASS_MAX_DAYS {{ cis_pass['max_days'] }}"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE  

- name: 5.4.1.1|Ensure password expiration is 365 days or less 
  shell: "chage --maxdays {{ cis_pass['max_days'] }} {{ item }}"
  with_items: "{{ task_5_4_1_1.stdout_lines|default([]) }}"
  check_mode: no
  changed_when: no  
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE  