---

- name: 5.6|Ensure access to the su command is restricted 
  lineinfile:
    state: present
    path: /etc/pam.d/su
    regexp: "^(#)?auth\\s.*\\spam_wheel.so"
    line: 'auth           required        pam_wheel.so use_uid'
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE

- name: 5.6|Ensure access to the su command is restricted 
  user:
    name: "{{ item }}"
    groups: wheel
  with_items: "{{ cis_wheel_group_members }}"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE