---

- name: 5.1.8|Ensure at/cron is restricted to authorized users 
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/at.deny
    - /etc/cron.deny
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

- name: 5.1.8|Check if at.allow exists
  stat:
    path: /etc/at.allow
  register: task_5_1_8_a
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

- name: 5.1.8|Check if cron.allow exists
  stat:
    path: /etc/cron.allow
  register: task_5_1_8_b
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE    

- name: 5.1.8|Ensure at/cron is restricted to authorized users
  file:
    dest: /etc/at.allow
    state: '{{ "file" if  task_5_1_8_a.stat.exists else "touch" }}'
    owner: root
    group: root
    mode: 0600
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE    
      
- name: 5.1.8|Ensure at/cron is restricted to authorized users
  file:
    dest: /etc/cron.allow
    state: '{{ "file" if  task_5_1_8_b.stat.exists else "touch" }}'
    owner: root
    group: root
    mode: 0600    
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE      