---

- name: 5.1.3|Ensure permissions on /etc/cron.hourly are configured 
  file:
      dest: /etc/cron.hourly
      state: directory
      owner: root
      group: root
      mode: 0700
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE  