---

- name: 5.1.4|Ensure permissions on /etc/cron.daily are configured 
  file:
    dest: /etc/cron.daily
    state: directory
    owner: root
    group: root
    mode: 0700
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE    