---

- name: 5.2.13|Ensure SSH LoginGraceTime is set to one minute or less 
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: "(?i)^(#)?LoginGraceTime\\s+"
    line: "LoginGraceTime {{ cis_sshd['logingracetime'] }}"
  notify: restart sshd 
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE
    