---

- name: 5.2.12|Ensure SSH Idle Timeout Interval is configured 
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: "(?i)^ClientAliveInterval\\s+"
    line: "ClientAliveInterval {{ cis_sshd['clientaliveinterval'] }}"
  notify: restart sshd 
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE

- name: 5.2.12|Ensure SSH Idle Timeout Interval is configured 
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: "(?i)^(#)?ClientAliveCountMax\\s+"
    line: "ClientAliveCountMax {{ cis_sshd['clientalivecountmax'] }}"
  notify: restart sshd         
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE     