---


- name: 5.4.5|Ensure default user shell timeout is 900 seconds or less 
  lineinfile:
    regexp: "^TMOUT\\s+"
    line: "TMOUT=600"
    path: "{{ item }}"
  with_items: 
    - /etc/bashrc
    - /etc/profile
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE  