---

- name: 5.4.1.3|Ensure password expiration warning days is 7 or more 
  lineinfile:
    state: present
    path: /etc/login.defs
    regexp: "^PASS_WARN_AGE\\s+"
    line: "PASS_WARN_AGE {{ cis_pass['warn_age'] }}"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE    

- name: 5.4.1.3|Ensure password expiration warning days is 7 or more 
  shell: "chage --warndays {{ cis_pass['warn_age'] }} {{ item }}"
  with_items: "{{ task_5_4_1_1.stdout_lines|default([]) }}"
  check_mode: no
  changed_when: no
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE  