---

- name: 5.4.2|Ensure system accounts are non-login
  shell: "awk -F: '($3 < {{ cis_rule_5_4_2_min_uid }}) {print $1 }' /etc/passwd | grep -v ^#"
  changed_when: no
  check_mode: no
  register: task_5_4_2
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE   

- name: 5.4.2|Ensure system accounts are non-login
  user:
    name: "{{ item }}"
    password_lock: true
  when: item != "root"
  with_items: "{{ task_5_4_2.stdout_lines }}"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE  

- name: 5.4.2|Ensure system accounts are non-login
  user:
    name: "{{ item }}"
    shell: /sbin/nologin
  when: "item not in rhel7cis_skip_lock_users"    
  with_items: "{{ task_5_4_2.stdout_lines }}"
  check_mode: no
  changed_when: no  
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE