---

- name: 6.1.2|Ensure permissions on /etc/passwd are configured 
  file:
    dest: /etc/passwd
    owner: root
    group: root
    mode: 0644
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE  