---

- name: 6.1.7|Ensure permissions on /etc/shadow- are configured 
  file:
    dest: /etc/shadow-
    owner: root
    group: root
    mode: 0000
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE 