---

- name: 6.2.7|Ensure all users' home directories exist
  script: audit_6.2.7.sh
  args: 
    executable: bash -l
  check_mode: no
  changed_when: 
    - audit_6_2_7.stdout_lines is defined 
    - audit_6_2_7.stdout_lines|length > 1
  register: audit_6_2_7
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE  
    
- name: 6.2.7|Ensure all users' home directories exist
  user:
    name: "{{ item.split(':')[0] }}"
    home: "{{ item.split(':')[1] }}"
  when: 
    - audit_6_2_7.stdout_lines is defined 
    - audit_6_2_7.stdout_lines|length > 1
    - item != ""
  with_items: "{{ audit_6_2_7.stdout_lines }}"
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE  