---

- name: 6.2.10|Ensure users' dot files are not group or world writable
  script: audit_6.2.10.sh
  args: 
    executable: bash -l
  check_mode: no
  changed_when: 
    - audit_6_2_10.stdout_lines is defined 
    - audit_6_2_10.stdout_lines|length > 1
  register: audit_6_2_10
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE 

- name: 6.2.10|Ensure users' dot files are not group or world writable
  fail:
    msg: "{{ audit_6_2_10.stdout_lines | join('\n')}}"
  when:
    - audit_6_2_10.stdout_lines is defined 
    - audit_6_2_10.stdout_lines|length > 1
    - fail_on_manual_remediation_actions
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE 

- name: 6.2.10|Ensure users' dot files are not group or world writable
  debug:
    msg: "{{ audit_6_2_10.stdout_lines | join('\n')}}"
  when:
    - audit_6_2_10.stdout_lines is defined 
    - audit_6_2_10.stdout_lines|length > 1
    - not fail_on_manual_remediation_actions
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE 