---

- name: 6.2.13|Ensure users' .netrc Files are not group or world accessible
  script: audit_6.2.13.sh
  args: 
    executable: bash -l
  check_mode: no
  changed_when: 
    - audit_6_2_13.stdout_lines is defined 
    - audit_6_2_13.stdout_lines|length > 1
  register: audit_6_2_13
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE 

- name: 6.2.13|Ensure users' .netrc Files are not group or world accessible
  file:
    mode: 0600
    dest: "{{ item }}"
  when: 
    - audit_6_2_13.stdout_lines is defined 
    - audit_6_2_13.stdout_lines|length > 1
    - item != ""
    - ('FAILED' not in item)
  with_items: "{{ audit_6_2_13.stdout_lines }}"
  tags:
    - scored
    - Level_Server
    - Level_Workstation
    - RULE  





# - name: 6.2.13|Ensure users' .netrc Files are not group or world accessible
#   script: audit_6.2.13.sh
#   check_mode: no
#   changed_when: False
#   register: audit_6_2_13
#   tags:
#     - scored
#     - Level_Server
#     - Level_Workstation
#     - RULE

# - name: 6.2.13|Ensure users' .netrc Files are not group or world accessible
#   fail:
#     msg: "{{ audit_6_2_13.stdout_lines }}"
#   when:
#     - audit_6_2_13.stdout_lines is defined and audit_6_2_13.stdout_lines|length > 0
#     - fail_on_manual_remediation_actions
#   tags:
#     - scored
#     - Level_Server
#     - Level_Workstation
#     - RULE

# - name: 6.2.13|Ensure users' .netrc Files are not group or world accessible
#   debug:
#     msg: "{{ audit_6_2_13.stdout_lines }}"
#   when:
#     - audit_6_2_13.stdout_lines is defined and audit_6_2_13.stdout_lines|length > 0
#     - not fail_on_manual_remediation_actions
#   tags:
#     - scored
#     - Level_Server
#     - Level_Workstation
#     - RULE