---

- name: 4.1.13|Ensure successful file system mounts are collected 
  template:
    src: audit/rhel7cis_rule_4_1_13.rules.j2
    dest: /etc/audit/rules.d/rhel7cis_rule_4_1_13.rules
    owner: root
    group: root
    mode: 0600
  notify: restart auditd
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation
    - RULE    