---

- name: 4.1.9|Ensure session initiation information is collected 
  template:
    src: audit/rhel7cis_rule_4_1_9.rules.j2
    dest: /etc/audit/rules.d/rhel7cis_rule_4_1_9.rules
    owner: root
    group: root
    mode: 0600
  notify: restart auditd
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation
    - RULE   