---

- name: 4.1.1.2|Ensure system is disabled when audit logs are full 
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} = {{ item.value }}"
    state: present
  with_items:
    - {key: space_left_action, value: email}
    - {key: action_mail_acct, value: root}
    - {key: admin_space_left_action, value: halt}
  notify: restart auditd
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation
    - RULE 