---

- name: 4.1.4|Ensure events that modify date and time information are collected 
  template:
    src: audit/rhel7cis_rule_4_1_4.rules.j2
    dest: /etc/audit/rules.d/rhel7cis_rule_4_1_4.rules
    owner: root
    group: root
    mode: 0600
  notify: restart auditd
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation
    - RULE   