---

- name: 4.1.16|Ensure system administrator actions (sudolog)
  template:
    src: audit/rhel7cis_rule_4_1_16.rules.j2
    dest: /etc/audit/rules.d/rhel7cis_rule_4_1_16.rules
    owner: root
    group: root
    mode: 0600
  notify: restart auditd
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation
    - RULE   