---

- name: 4.1.1.3|Ensure audit logs are not automatically deleted 
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: "^max_log_file_action"
    line: "max_log_file_action = keep_logs"
    state: present
  notify: restart auditd
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation
    - RULE 