---

- name: 4.1.2|Ensure auditd service is enabled 
  yum:
    name: audit
    state: present
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation
    - RULE 

- name: 4.1.2|Ensure auditd service is enabled 
  service:
    name: auditd
    state: started
    enabled: yes
  tags:
    - scored
    - Level2_Server
    - Level2_Workstation
    - RULE 