---

- name: 4.2.2.1|Ensure syslog-ng service is enabled 
  yum:
    name: syslog-ng
    state: present
  when: cis_enable_syslog_ng
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE

# - name: 4.2.2.1|Ensure syslog-ng service is enabled 
#   shell: systemctl is-enabled syslog-ng 2> /dev/null | grep -e 'enabled\|disabled' || echo 'error'
#   register: syslog_ng_4_2_2_1
    
- name: 4.2.2.1|Ensure syslog-ng service is enabled 
  service:
    name: syslog-ng
    enabled: yes
    state: started  
  when: cis_enable_syslog_ng
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 