---

- name: 4.2.2.2|Ensure logging is configured 
  lineinfile:
    path: /etc/syslog-ng/syslog-ng.conf
    line: "{{ item.value }}"
    state: present
  notify: restart syslog-ng
  with_items:
    - {value: "log { source(src); source(chroots); filter(f_console); destination(console); };"}
    - {value: "log { source(src); source(chroots); filter(f_console); destination(xconsole); };"}
    - {value: "log { source(src); source(chroots); filter(f_newscrit); destination(newscrit); };"}
    - {value: "log { source(src); source(chroots); filter(f_newserr); destination(newserr); };"}
    - {value: "log { source(src); source(chroots); filter(f_newsnotice); destination(newsnotice); };"}
    - {value: "log { source(src); source(chroots); filter(f_mailinfo); destination(mailinfo); };"}
    - {value: "log { source(src); source(chroots); filter(f_mailwarn); destination(mailwarn); };"}
    - {value: "log { source(src); source(chroots); filter(f_mailerr); destination(mailerr);}"}
    - {value: "log { source(src); source(chroots); filter(f_mail); destination(mail); };"}
    - {value: "log { source(src); source(chroots); filter(f_acpid); destination(acpid); flags(final); };"}
    - {value: "log { source(src); source(chroots); filter(f_acpid_full); destination(devnull); flags(final); };"}
    - {value: "log { source(src); source(chroots); filter(f_acpid_old); destination(acpid); flags(final); };"}
    - {value: "log { source(src); source(chroots); filter(f_netmgm); destination(netmgm); flags(final); };"}
    - {value: "log { source(src); source(chroots); filter(f_local); destination(localmessages); };"}
    - {value: "log { source(src); source(chroots); filter(f_messages); destination(messages); };"}
    - {value: "log { source(src); source(chroots); filter(f_iptables); destination(firewall); };"}
    - {value: "log { source(src); source(chroots); filter(f_warn); destination(warn); };"}
  when: cis_enable_syslog_ng
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation
    - RULE  