---

- name: 4.2.1.2|Ensure logging is configured 
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: "{{ item.pattern }}"
    line: "{{ item.value }}"
    state: present
  notify: restart rsyslog
  when: cis_enable_rsyslog
  with_items:
    - {pattern: "^\\*\\.emerg",                       value: "*.emerg                           :omusrmsg:*"}
    - {pattern: "^mail\\.\\*",                        value: "mail.*                            -/var/log/mail"}
    - {pattern: "^mail\\.info",                       value: "mail.info                         -/var/log/mail.info"}
    - {pattern: "^mail\\.warning",                    value: "mail.warning                      -/var/log/mail.warn"}
    - {pattern: "^mail\\.err",                        value: "mail.err                          /var/log/mail.err"}
    - {pattern: "^news\\.crit",                       value: "news.crit                         -/var/log/news/news.crit"}
    - {pattern: "^news\\.err",                        value: "news.err                          -/var/log/news/news.err"}
    - {pattern: "^news\\.notice",                     value: "news.notice                       -/var/log/news/news.notice"}
    - {pattern: "^\\*\\.=warning;\\*\\.=err",         value: "*.=warning;*.=err                 -/var/log/warn"}
    - {pattern: "^\\*\\.crit",                        value: "*.crit                            /var/log/warn"}
    - {pattern: "^\\*\\.\\*;mail\\.none;news\\.none", value: "*.*;mail.none;news.none           -/var/log/messages"}
    - {pattern: "^local0,local1\\.\\*",               value: "local0,local1.*                   -/var/log/localmessages"}
    - {pattern: "^local2,local3\\.\\*",               value: "local2,local3.*                   -/var/log/localmessages"}
    - {pattern: "^local4,local5\\.\\*",               value: "local4,local5.*                   -/var/log/localmessages"}
    - {pattern: "^local6,local7\\.\\*",               value: "local6,local7.*                   -/var/log/localmessages"}
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation
    - RULE 