---

- name: 4.2.1.5|Ensure remote rsyslog messages are only accepted on designated log hosts. 
  lineinfile:
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    path: "/etc/rsyslog.conf"
    state: present
  when: 
    - cis_rsyslog_accept_remote_messages 
    - cis_enable_rsyslog
  with_items:
    - { regexp: "^(#)?\\$ModLoad\\s+imtcp.so", line: "$ModLoad imtcp.so" }
    - { regexp: "^(#)?\\$InputTCPServerRun\\s+", line: "$InputTCPServerRun 514" }
  notify: restart rsyslog
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation
    - RULE   

- name: 4.2.1.5|Ensure remote rsyslog messages are only accepted on designated log hosts. 
  lineinfile:
    regexp: "{{ item }}"
    path: "/etc/rsyslog.conf"
    state: absent
  when: 
    - not cis_rsyslog_accept_remote_messages 
    - cis_enable_rsyslog
  with_items:
    - "^(#)?\\$ModLoad\\s+imtcp.so"
    - "^(#)?\\$InputTCPServerRun\\s+514"
  notify: restart rsyslog
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation
    - RULE 