---

- name: 4.2.2.5|Ensure remote syslog-ng messages are only accepted on designated log hosts
  lineinfile:
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    path: /etc/syslog-ng/syslog-ng.conf
    state: present  
  with_items:
    - { regexp: "^(#)?source net", line: "source net{ tcp(); };" }
    - { regexp: "^(#)?destination remote", line: "destination remote { file(\"/var/log/remote/${FULLHOST}-log\"); };" }
    - { regexp: "^(#)?log \\{ source\\(net\\)\\;", line: "log { source(net); destination(remote); };" }
  when: 
    - cis_syslogng_accept_remote_messages 
    - cis_enable_syslog_ng    
  notify: restart syslog-ng
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation
    - RULE 

- name: 4.2.2.5|Ensure remote syslog-ng messages are only accepted on designated log hosts
  lineinfile:
    regexp: "{{ item }}"
    path: /etc/syslog-ng/syslog-ng.conf
    state: absent
  when: 
    - not cis_syslogng_accept_remote_messages 
    - cis_enable_syslog_ng
  with_items:
    - { regexp: "^(#)?source net" }
    - { regexp: "^(#)?destination remote" }
    - { regexp: "^(#)?log \\{ source\\(net\\)\\;" }
  notify: restart syslog-ng
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation
    - RULE     