---

- name: 4.2.1.3|Ensure rsyslog default file permissions configured 
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: "^\\$FileCreateMode"
    line: '$FileCreateMode 0640'
  notify: restart rsyslog
  when: cis_enable_rsyslog 
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE 