---

- name: 2.1.3|Ensure discard services are not enabled
  stat:
    path: /etc/xinetd.d/discard-dgram
  register: task_2_1_3_a
  changed_when: no
  tags:
    - PRE_TASK

- name: 2.1.3|Ensure discard services are not enabled
  shell: chkconfig --list discard-dgram 2>/dev/null | grep -q "on" && echo "True" || echo "False"
  when: task_2_1_3_a.stat.exists
  register: task_2_1_3_b
  changed_when: task_2_1_3_b.stdout == "True"
  check_mode: no
  tags:
    - PRE_TASK

- name: 2.1.3|Ensure discard services are not enabled
  shell: chkconfig discard-dgram off
  notify: restart xinetd
  check_mode: no
  changed_when: no  
  when: 
    - task_2_1_3_a.stat.exists
    - task_2_1_3_b.stdout == "True"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE  
  
- name: 2.1.3|Ensure discard services are not enabled
  stat:
    path: /etc/xinetd.d/discard-stream
  register: task_2_1_3_c
  changed_when: no
  tags:
    - PRE_TASK

- name: 2.1.3|Ensure discard services are not enabled
  shell: chkconfig --list discard-stream 2>/dev/null | grep -q "on" && echo "True" || echo "False"
  when: task_2_1_3_c.stat.exists
  register: task_2_1_3_d
  changed_when: task_2_1_3_d.stdout == "True"
  check_mode: no
  tags:
    - PRE_TASK

- name: 2.1.3|Ensure discard services are not enabled
  shell: chkconfig discard-stream off
  notify: restart xinetd
  check_mode: no
  changed_when: no  
  when: 
    - task_2_1_3_c.stat.exists
    - task_2_1_3_d.stdout == "True"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE