---

- name: 2.1.2|Ensure daytime services are not enabled
  stat:
    path: /etc/xinetd.d/daytime-dgram
  register: task_2_1_2_a
  changed_when: no
  tags:
    - PRE_TASK

- name: 2.1.2|Ensure daytime services are not enabled
  shell: chkconfig --list daytime-dgram 2>/dev/null | grep -q "on" && echo "True" || echo "False"
  when: task_2_1_2_a.stat.exists
  register: task_2_1_2_b
  changed_when: task_2_1_2_b.stdout == "True"
  check_mode: no
  tags:
    - PRE_TASK

- name: 2.1.2|Ensure daytime services are not enabled
  shell: chkconfig daytime-dgram off
  notify: restart xinetd
  when: 
    - task_2_1_2_a.stat.exists
    - task_2_1_2_b.stdout == "True"
  check_mode: no
  changed_when: no    
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE  
  
- name: 2.1.2|Ensure daytime services are not enabled
  stat:
    path: /etc/xinetd.d/daytime-stream
  register: task_2_1_2_c
  changed_when: no
  tags:
    - PRE_TASK
    
- name: 2.1.2|Ensure daytime services are not enabled
  shell: chkconfig --list daytime-stream 2>/dev/null | grep -q "on" && echo "True" || echo "False"
  when: task_2_1_2_c.stat.exists
  register: task_2_1_2_d
  changed_when: task_2_1_2_d.stdout == "True"
  check_mode: no
  tags:
    - PRE_TASK

- name: 2.1.2|Ensure daytime services are not enabled
  shell: chkconfig daytime-stream off
  notify: restart xinetd
  when: 
    - task_2_1_2_c.stat.exists
    - task_2_1_2_d.stdout == "True"
  check_mode: no
  changed_when: no    
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE