---

- name: 2.2.14|Ensure SNMP Server is not enabled 
  service:
    name: snmpd
    state: stopped
    enabled: no  
  when: snmpd_service_status.stdout == "loaded" 
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE