---

- name: 2.2.1.3|Ensure chrony is configured
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: Restart chronyd
  when: cis_time_synchronization == "chrony"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE

- name: 2.2.1.3|Ensure chrony is configured
  lineinfile:
    path: /etc/sysconfig/chronyd
    regexp: "^(#)?OPTIONS"
    line: "OPTIONS=\"-u chrony\""
    state: present
    create: yes
  when: cis_time_synchronization == "chrony"
  tags:
    - not_scored
    - Level1_Server
    - Level1_Workstation
    - RULE