---

- name: 2.2.18|Ensure talk server is not enabled 
  service:
    name: ntalk
    state: stopped
    enabled: no     
  when: ntalk_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level1_Workstation
    - RULE