---

- name: 2.2.4|Ensure CUPS is not enabled 
  service:
    name: cups
    state: stopped
    enabled: no
  when: cups_service_status.stdout == "loaded"
  tags:
    - scored
    - Level1_Server
    - Level2_Workstation
    - RULE